//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientProfile
    {
        public int id_client { get; set; }
        public string client_name { get; set; }
        public string address { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public int fk_state { get; set; }
        public string zip { get; set; }
        public string zip_4 { get; set; }
        public int fk_company_location { get; set; }
    
        public virtual CompanyLocation CompanyLocation { get; set; }
        public virtual State State { get; set; }
    }
}
