//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timesheet.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int id_projects { get; set; }
        public string ProjectName { get; set; }
        public string ProjectNumber { get; set; }
        public string Notes { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<System.DateTime> deleted_on { get; set; }
        public int fk_client { get; set; }
        public int fk_created_by { get; set; }
    
        public virtual ClientProfile ClientProfile { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
